; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = T_BEAM_SX1276
boards_dir = boards

[esp32_base]
build_flags = 
	${env.build_flags}

[env:T_BEAM_SX1276]
platform = espressif32@6.9.0
framework = arduino
board = esp32dev
upload_speed = 921600
monitor_speed = 115200
monitor_filters = 
	default
	esp32_exception_decoder
board_build.partitions = huge_app.csv
test_build_src = false
build_flags = 
	-DT_BEAM_SX1276
	-mfix-esp32-psram-cache-issue
	-DBOARD_HAS_PSRAM
	-I include
	-DUNIT_TEST
lib_deps = 
	mikalhart/TinyGPSPlus@^1.1.0
	lewisxhe/XPowersLib@^0.3.1
	jgromes/RadioLib@^7.4.0

check_tool = cppcheck
check_flags =
    cppcheck: --enable=all --inconclusive