[platformio]
default_envs = T_BEAM_SX1276
boards_dir = boards

[env]
platform = espressif32@6.9.0
framework = arduino
upload_speed = 921600
monitor_speed = 115200
monitor_filters =
    default
    esp32_exception_decoder

[esp32_base]
build_flags =
    ${env.build_flags}

[env:T_BEAM_SX1276]
board = esp32dev
build_flags = ${esp32_base.build_flags}
    -DT_BEAM_SX1276
    -mfix-esp32-psram-cache-issue
    -DBOARD_HAS_PSRAM
board_build.partitions = huge_app.csv
lib_deps =
    olikraus/U8g2@^2.35.9
